### ISSUE TITLE
Null reference 오류가 발생하면서 더이상 맵 동작이 되지 않는 현상

### ISSUE THREAD

**Issue by skult82** [johyunchol/kakao_map_plugin#1]
setState() { } 를 계속 호출하다 보면 어느 순간에 Null Reference 가 발생하고, 그 이후 부터는 이벤트는 들어오지만 setCenter 와 같은 맵의 제어가 되지 않습니다.

``` dart
List<Marker> _markers = [];

...

KakaoMap(
  onMapCreated: _onMapCreated,
  markers: _markers,
  center: LatLng(37.3608681, 126.9306506),
  onMarkerTap: _onMarkerTapped,
  onMapTap: _onMapTapped,
  onCenterChangeCallback: _onCenterChanged,
)

...

FloatingActionButton(
  onPressed: () {
    setState(() {

    });
    debugPrint("setState is called");
  },
  heroTag: "addNewHistory",
  child: const Icon(Icons.add),
)

...

```

```
I/flutter (16442): setState is called
E/FrameEvents(16442): updateAcquireFence: Did not find frame.
E/FrameEvents(16442): updateAcquireFence: Did not find frame.
E/FrameEvents(16442): updateAcquireFence: Did not find frame.
E/FrameEvents(16442): updateAcquireFence: Did not find frame.
E/FrameEvents(16442): updateAcquireFence: Did not find frame.
E/flutter (16442): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.evaluateJavascript(java.lang.String, android.webkit.ValueCallback)' on a null object reference, Cause: null, Stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.evaluateJavascript(java.lang.String, android.webkit.ValueCallback)' on a null object reference
E/flutter (16442): 	at io.flutter.plugins.webviewflutter.WebViewHostApiImpl.evaluateJavascript(WebViewHostApiImpl.java:427)
E/flutter (16442): 	at io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$-CC.lambda$setup$13(GeneratedAndroidWebView.java:1044)
E/flutter (16442): 	at io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$$ExternalSyntheticLambda22.onMessage(Unknown Source:2)
E/flutter (16442): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
E/flutter (16442): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (16442): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter (16442): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (16442): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (16442): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (16442): 	at android.os.Looper.loopOnce(Looper.java:226)
E/flutter (16442): 	at android.os.Looper.loop(Looper.java:313)
E/flutter (16442): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/flutter (16442): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (16442): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/flutter (16442): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/flutter (16442): , null)
E/flutter (16442): #0      WebViewHostApi.evaluateJavascript (package:webview_flutter_android/src/android_webview.pigeon.dart:639:7)
E/flutter (16442): <asynchronous suspension>
E/flutter (16442): #1      WebViewAndroidPlatformController.runJavascript (package:webview_flutter_android/webview_android_widget.dart:296:5)
E/flutter (16442): <asynchronous suspension>
E/flutter (16442): #2      KakaoMapController.addMarker (package:kakao_map_plugin/src/basic/kakao_map_controller.dart:61:9)
E/flutter (16442): <asynchronous suspension>
E/flutter (16442): 
E/FrameEvents(16442): updateAcquireFence: Did not find frame.
I/ViewRootImpl@e982556[MainActivity](16442): ViewPostIme pointer 0
I/ViewRootImpl@e982556[MainActivity](16442): ViewPostIme pointer 1
I/flutter (16442): setState is called
E/flutter (16442): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.evaluateJavascript(java.lang.String, android.webkit.ValueCallback)' on a null object reference, Cause: null, Stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.evaluateJavascript(java.lang.String, android.webkit.ValueCallback)' on a null object reference
E/flutter (16442): 	at io.flutter.plugins.webviewflutter.WebViewHostApiImpl.evaluateJavascript(WebViewHostApiImpl.java:427)
E/flutter (16442): 	at io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$-CC.lambda$setup$13(GeneratedAndroidWebView.java:1044)
E/flutter (16442): 	at io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$$ExternalSyntheticLambda22.onMessage(Unknown Source:2)
E/flutter (16442): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
E/flutter (16442): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (16442): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter (16442): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (16442): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (16442): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (16442): 	at android.os.Looper.loopOnce(Looper.java:226)
E/flutter (16442): 	at android.os.Looper.loop(Looper.java:313)
E/flutter (16442): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/flutter (16442): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (16442): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/flutter (16442): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/flutter (16442): , null)
E/flutter (16442): #0      WebViewHostApi.evaluateJavascript (package:webview_flutter_android/src/android_webview.pigeon.dart:639:7)
E/flutter (16442): <asynchronous suspension>
E/flutter (16442): #1      WebViewAndroidPlatformController.runJavascript (package:webview_flutter_android/webview_android_widget.dart:296:5)
E/flutter (16442): <asynchronous suspension>
E/flutter (16442): 
E/flutter (16442): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.evaluateJavascript(java.lang.String, android.webkit.ValueCallback)' on a null object reference, Cause: null, Stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.evaluateJavascript(java.lang.String, android.webkit.ValueCallback)' on a null object reference
E/flutter (16442): 	at io.flutter.plugins.webviewflutter.WebViewHostApiImpl.evaluateJavascript(WebViewHostApiImpl.java:427)
E/flutter (16442): 	at io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$-CC.lambda$setup$13(GeneratedAndroidWebView.java:1044)
E/flutter (16442): 	at io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$$ExternalSyntheticLambda22.onMessage(Unknown Source:2)
E/flutter (16442): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
E/flutter (16442): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (16442): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter (16442): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (16442): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (16442): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (16442): 	at android.os.Looper.loopOnce(Looper.java:226)
E/flutter (16442): 	at android.os.Looper.loop(Looper.java:313)
E/flutter (16442): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/flutter (16442): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (16442): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/flutter (16442): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/flutter (16442): , null)
E/flutter (16442): #0      WebViewHostApi.evaluateJavascript (package:webview_flutter_android/src/android_webview.pigeon.dart:639:7)
E/flutter (16442): <asynchronous suspension>
E/flutter (16442): #1      WebViewAndroidPlatformController.runJavascript (package:webview_flutter_android/webview_android_widget.dart:296:5)
E/flutter (16442): <asynchronous suspension>
E/flutter (16442): #2      KakaoMapController.addMarker (package:kakao_map_plugin/src/basic/kakao_map_controller.dart:61:9)
E/flutter (16442): <asynchronous suspension>
E/flutter (16442): 
I/ViewRootImpl@e982556[MainActivity](16442): ViewPostIme pointer 0
I/ViewRootImpl@e982556[MainActivity](16442): ViewPostIme pointer 1

```

**Comment by johyunchol** [comment]
올려주신대로 저도 테스트를 해 보았는데 같은 현상이 발생하지 않고 있는 상황입니다.

1. setState 를 계속 호출한다는게 어느정도의 호출일까요?
2. 혹시 Android, iOS 중 어떤걸로 하신걸까요? 로그상에는 android 로 보이긴 하는데 맞는지요?
3. 시뮬레이터에서 하신건가요? 아니면 실 기기에서 하신걸까요?

구체적인 정보를 알아야 더 테스트 및 수정이 가능 할 것 같습니다!

**Comment by skult82** [comment]
> setState** 를 계속 호출한다는게 어느정도의 호출일까요?

다시 테스트 해보니 setState 의 호출 빈도에 따른 현상은 아닌 것 같습니다. 한두번의 호출만에 발생하는 경우도 있고, 수십번 호출해야 발생하는 경우도 있습니다.

> 혹시 Android, iOS 중 어떤걸로 하신걸까요? 로그상에는 android 로 보이긴 하는데 맞는지요?

네, 안드로이드에서 테스트 하였습니다.

> 시뮬레이터에서 하신건가요? 아니면 실 기기에서 하신걸까요?

실 기기에서 진행을 하였습니다. 기기는 Galaxy Z Flip 4 이며, 안드로이드 버전은 13 입니다.

IDE 는 안드로이드 스튜디오를 사용하고 있고, 케이블로 직접 연결하여 Run (Ctrl+F5) 커맨드를 사용하여 기기에서 테스트를 진행하고 있습니다.
그런데 오늘 코멘트를 보고 추가 테스트를 해보기 위해 앱을 삭제하고 다시 빌드를 했더니 아직까지는 동일한 현상이 발생하지 않고 있습니다.
아마도 테스트 환경에서 발생하는 일종의 안드로이드 운영체제의 버그인 것 같습니다.
본 이슈는 해소됨으로 변경하도록 하겠습니다.
