### ISSUE TITLE
PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript....)

### ISSUE THREAD

**Issue by tngudzzz** [johyunchol/kakao_map_plugin#30]
안녕하세요.
addMaker 관련해서 오류가 발생해서 문의드립니다.
오류 로그를 보니 자바스크립트에서 발생하는 문제인거 같습니다.

PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., A JavaScript exception occurred (WKErrorDomain:4:{WKJavaScriptExceptionLineNumber: Unsupported Type: 1, WKJavaScriptExceptionMessage: ReferenceError: Can't find variable: addMarker, WKJavaScriptExceptionSourceURL: Unsupported Type: undefined, NSLocalizedDescription: A JavaScript exception occurred, WKJavaScriptExceptionColumnNumber: Unsupported Type: 10}), null)

1. webkit_webview_controller.dart in WebKitWebViewController.runJavaScript at line 407:7 within webview_flutter_wkwebview
2. web_kit_api_impls.dart in WKWebViewHostApiImpl.evaluateJavaScriptForInstances at line 1061:7 within webview_flutter_wkwebview

확인부탁드리겠습니다.
감사합니다.

**Comment by johyunchol** [comment]
제가 답변이 늦어서 죄송합니다.

해당 부분 확인 해 보도록 하겠습니다!

**Comment by kindkmj** [comment]
폴리곤 등록시에도 
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., A JavaScript exception occurred (WKErrorDomain:4:{WKJavaScriptExceptionLineNumber: Unsupported Type: 251, WKJavaScriptExceptionMessage: TypeError: null is not an object (evaluating 'list.length'), WKJavaScriptExceptionSourceURL: Unsupported Type: about:blank, NSLocalizedDescription: A JavaScript exception occurred, WKJavaScriptExceptionColumnNumber: Unsupported Type: 29}), null)
#0      WKWebViewHostApiImpl.evaluateJavaScriptForInstances (package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart:1123:7)
<asynchronous suspension>
#1      WebKitWebViewController.runJavaScript (package:webview_flutter_wkwebview/src/webkit_webview_controller.dart:462:7)
<asynchronous suspension>
#2      KakaoMapController.addPolyline (package:kakao_map_plugin/src/basic/kakao_map_controller.dart:15:9)
<asynchronous suspension>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., A JavaScript exception occurred (WKErrorDomain:4:{WKJavaScriptExceptionLineNumber: Unsupported Type: 251, WKJavaScriptExceptionMessage: TypeError: null is not an object (evaluating 'list.length'), WKJavaScriptExceptionSourceURL: Unsupported Type: about:blank, NSLocalizedDescription: A JavaScript exception occurred, WKJavaScriptExceptionColumnNumber: Unsupported Type: 29}), null)
#0      WKWebViewHostApiImpl.evaluateJavaScriptForInstances (package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart:1123:7)
<asynchronous suspension>
#1      WebKitWebViewController.runJavaScript (package:webview_flutter_wkwebview/src/webkit_webview_controller.dart:462:7)
<asynchronous suspension>
#2      KakaoMapController.addPolyline (package:kakao_map_plugin/src/basic/kakao_map_controller.dart:15:9)
<asynchronous suspension>

해당 오류가 나옵니다!

**Comment by kindkmj** [comment]
controller에  addPolyline으로 하면 에러가 안나오지만 
KakaoMap에 초기값으로 폴리라인을 등록하면 해당 에러가 발생하네요!

**Comment by seunghwanly** [comment]
`CustomOverlay`도 동일한 이슈 발생합니다! 👀 

### Debug 화면

- addCustomOverlay 함수 실행 시 발생
<img width="745" alt="Debug#1 - addCustomOverlay 에러" src="https://github.com/johyunchol/kakao_map_plugin/assets/22142225/ac78037e-23eb-4405-9a10-c89f64c4f8e2">

- 생성된 CustomOverlay
<img width="444" alt="Debug#2 - 생성된 CustomOverlay" src="https://github.com/johyunchol/kakao_map_plugin/assets/22142225/f82f72fb-99a3-48da-bc61-95594eed3d25">

- runJavaScript 에러 발생
<img width="739" alt="JS Exception" src="https://github.com/johyunchol/kakao_map_plugin/assets/22142225/192ff864-db56-4a82-98b9-7b6f5ac9870e">

**Comment by johyunchol** [comment]
@tngudzzz @kindkmj @seunghwanly 님 감사합니다.

해당 내용 수정가능 한 방향으로 수정하도록 하겠습니다!
